### ISSUE TITLE
Visualization Tweaks

### ISSUE THREAD

**Issue by thompsct** [SemBioProcess/SemGen#212]
Left Menu:
- [x] Highlight active visualization type for a model
- [x] Change font size for selected model and add subheader for actions.

Right Menu:

- [x] Link subheading doesn't have any children associated with it.
- [x] Add key for unspecified source or sink icon.

Other:

- [x] Distinguish Merger from main stage. (Maybe pale yellow or light gray background?)
- [x] Holding shift should create unique cursor.
- [x] Highlight active task icon
- [x] Hovering over task icon should produce a tooltip showing what it contains (see Max's idea for this in comments below)

**Comment by maxneal** [comment]
Rather than require the user to hover over an active task icon to get more details about the task, I was thinking of something like this to indicate to the user what each task icon (i.e. merging task) represents:
![junk](https://user-images.githubusercontent.com/3513016/28138572-1ee56c5c-6706-11e7-871e-dc5b96745129.png)

**Comment by maxneal** [comment]
From SG dev mtg: Introduce scrollers for the Node Key and Link Key components of the right flyout window in the Stage.

**Comment by thompsct** [comment]
All done in the Extractor branch.

**Comment by maxneal** [comment]
Chris can you make the edits to the visualization key so it looks like this:
(Note that the size of the nodes is reduced, too.)

![newvizkey](https://user-images.githubusercontent.com/3513016/29287243-aada6800-80e9-11e7-9d6c-cd2f8ed67d85.png)

**Comment by thompsct** [comment]
Redid the key menu as shown.
