### ISSUE TITLE
Integration with ontology lookup service

### ISSUE THREAD

**Issue by matthiaskoenig** [SemBioProcess/SemGen#324]
Currently, only a very limited set of ontologies is supported in SemGen.
It should be possible to directly use the content of the ontology lookup service (OLS, https://www.ebi.ac.uk/ols/index) 
- Important ontologies like CHEBI, GO, KEGG, Reactome, .... are currently not accessible.

**Comment by maxneal** [comment]
Historically, the main motivation behind SemGen's development has been to recognize when two models simulate the same biological feature. We have therefore intentionally limited the knowledge resources that can be used to annotate a model in SemGen in order to promote consistency between annotators and help ensure that two different annotators, when annotating the same biological feature, converge on an annotation that uses the same reference terms. That being said, we do in fact support access to ChEBI and GO (via BioPortal). Here's the list of ontologies users can access for different types of annotations or annotation components in SemGen:

**Singular annotations (limited to ontologies that represent physical _properties_):** 
- OPB
- PATO
- SBO
- SNOMED

**Composite annotation: physical property component (high-level physical properties)**
- OPB

**Composite annotations physical entity component (physical continuants)**
- ChEBI
- CL (Cell type ontology)
- FMA
- GO
- MA (Mouse adult gross anatomy)
- OBI
- OPB
- PR (Protein ontology)
- UniProt

**Composite annotations physical process component**
- (we recommend using a custom physical process that the user defines by indicating its participating physical entities, but users can import reference physical process terms from OPB and GO to attach "isVersionOf" statements to those custom processes. There's also a way to use a reference process instead of a custom process in this type of composite annotation by first importing it into the reference term library - let me know if you'd like to know how to do that.)

We've found that the ontologies listed here provide adequate coverage for annotating the biological concepts within the scores of test models we have annotated.

Hopefully this is helpful. What reference terms from KEGG or Reactome do you need that aren't provided by the resources listed above?

**Comment by matthiaskoenig** [comment]
Thanks for the explanation. I mainly use CHEBI, no need for KEGG and Reactome, just see this in many models.
So if I understand it correctly, I have to build a composite annotation to use CHEBI. I will try this and give you feedback if things are unclear.

**Comment by maxneal** [comment]
Correct: ChEBI can be accessed when a composite annotation is created for a property of a _physical entity_ (as opposed to properties of physical processes, physical forces, or physical dependencies).

Example of using ChEBI in a composite for a model variable that represents cytosolic calcium concentration in a cardiomyocyte:
OPB:Chemical concentration <propertyOf> **ChEBI:calcium(2+)** <partOf> FMA:Portion of cytosol <partOf> FMA:Cardiac myocyte

To build this composite, open a model in an Annotator Tab, select a codeword on the left-hand side. In the upper right dialog (blue background), select "Chemical concentration (OPB)" in the first drop-down list under "Composite annotation". Then you should see a second drop-down list below "property_of".  To the right of it are a bunch of icons. Click on the binoculars to search for a knowledge resource term. This will bring up a search dialog where you can select ChEBI from the top drop-down list and perform string searches over that ontology.

I have also seen KEGG and Reactome used in some BioModels. It's unclear to me why those are used. Maybe Reactome terms are primarily used for model-level annotations (like if you wanted to indicate that ModelX **as a whole** simulates some pathway represented in Reactome.)
